version: '3.9'

services:
  cucumber-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/cucumber-garden-quarkus-jar
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LANGUAGE: en_US:en
      JAVA_OPTS_APPEND: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
      JAVA_APP_JAR: /deployments/quarkus-run.jar
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/cucumber
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - '8080:8080'
    networks:
      - cucumber_network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./src/main/resources/sql-scripts/data.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - cucumber_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - '5433:5432' # This port mapping is only required for testing the database connection with PSQL from the host machine.
                    # The application running inside the Docker network will still function properly without this mapping,
                    # as it communicates with the database using the internal Docker network and the service name 'postgres'.
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: cucumber

networks:
  cucumber_network: